import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CountryProvider } from "./context/CountryContext";
import SmoothScroll from "./Components/UI/SmoothScroll";
import SilkBackgroundWrapper from "./Components/UI/SilkBackgroundWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        {/* Silk Background - covers entire website */}
        <SilkBackgroundWrapper />
        <CountryProvider>
          <SmoothScroll>
            {children}
          </SmoothScroll>
        </CountryProvider>
      </body>
    </html>
  );
}
